######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 16 21:56:52 2022
######################################################################

TEMPLATE = app
TARGET = Qt_GUI
INCLUDEPATH += .

QT += widgets

DEFINES += QT_DEPRECATED_WARNINGS
DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000

# Input
HEADERS += mainwidget.h
SOURCES += main.cpp mainwidget.cpp SocketClassClient.cpp
